version: "3.9"


services:
  app:
    build:
      context: . #Builds on current directory
      args:
        - DEV=true
    ports:
      - "8000:8000" #Maps port 8000 from local machine to port 8000 in server
    volumes:
    #Maps local files to server to sync changes
      - ./app:/app
    #Command use to run server
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
    #They should match the values defined below (db) section
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DV_PASS=changeme
    #Make sure that db starts first
    depends_on:
      - db

  db:
  #image from dockerhub
    image: postgres:13-alpine
    volumes:
    #Should matcht the name below
      - dev-db-data:/var/lib/postgresql/data
    #Set initial value for the local dev server
    environment: 
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme


#Adding volumes. 
volumes:
#Name of volume. no need to add name as docker compose will 
#take care of it.
  dev-db-data: 
