---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
      #Action that is provided by github actions
      #A docker container that is setup to perform a task
      #Here is an action that logs in to docker
        uses: docker/login-action@v1
      #These are parameters that are passed in the docker
      #login action
        with:
          username: ${{secret.DOCKERHUB_USER}}
          password: ${{secret.DOCKERHUB_TOKEN}}
      #Checks out our code for this job
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"